### ISSUE TITLE
Authorize and Get Message not working as expected through Java client.

### ISSUE THREAD

**Issue by dhana555std** [manybrain/mailinator-java-client#1]
Hi All,
          I tried to make the following API calls through post man client:-

- https://mailinator.com/api/v2/domains/{{domain}}?token={{token}}
- https://mailinator.com/api/v2/domains/{{domain}}?token={{token}}

They worked perfectly fine and I am able to get the messages. Nevertheless when I try the same through Java SDK, I get the following error as attached in the file below.

[MailinatorIssueswithSDK.txt](https://github.com/manybrain/mailinator-java-client/files/4911430/MailinatorIssueswithSDK.txt)

This is the code I have written:-

```
MailinatorClient mailinatorClient = new MailinatorClient(MAILINATOR_TOKEN);
Inbox inbox = mailinatorClient.request(new GetInboxRequest(DOMAIN));
System.out.println("Works!");
```

```
MailinatorClient mailinatorClient = new MailinatorClient(MAILINATOR_TOKEN);
Message m = mailinatorClient.request(
                new GetMessageRequest(DOMAIN, INBOX, MESSAGE_ID));

List<Part> parts = m.getParts();
String subject = m.getSubject();
Map<String, Object> headers = m.getHeaders();

```

Did I miss something?

**Comment by chetand24** [comment]
Right, its not working for me as well:

`
Exception in thread "main" java.lang.NoClassDefFoundError: javax/ws/rs/client/ClientBuilder
	at com.manybrain.mailinator.client.JerseyClient.<clinit>(JerseyClient.java:20)
	at com.manybrain.mailinator.client.message.GetMessageRequest.<clinit>(GetMessageRequest.java:22)
`

**Comment by rfvallina** [comment]
@dhana555std you are using apache cxf client which is not library dependency.
@chetand24 you didn't have required dependency. Probably you're using a self-executable binary which is a wrong approach. 

This library must be used as a dependency using maven or gradle.
